[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "review-assistant"
version = "0.0.1"
requires-python = ">=3.12"

[tool.setuptools.packages.find]
where = ["src"]